# Generated by Django 3.0.4 on 2020-03-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('DS', 'Disallowed'), ('RE', 'Rejected')], default=(('PE', 'Pending'), ('AP', 'Approved'), ('DS', 'Disallowed'), ('RE', 'Rejected')), max_length=12)),
                ('comment', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
