# Generated by Django 3.0.4 on 2020-03-14 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('DS', 'Disallowed'), ('RE', 'Rejected')], default=(('PE', 'Pending'), ('AP', 'Approved'), ('DS', 'Disallowed'), ('RE', 'Rejected')), max_length=12)),
                ('comment', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=None)),
                ('approved_by', models.ManyToManyField(through='actions.Action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.Request'),
        ),
        migrations.AddField(
            model_name='action',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
